name=JUXI_HeartRate_SPO2
version=1.0.0
sentence=JUXI Standard library.
paragraph=JUXI_Sensor is the standard library of JUXI.
category=Sensors
url=https://github.com/Juxi-Technology/JUXI_HeartRate_SPO2
architectures=*
